---
# Copyright 2016, Rackspace US, Inc.
#
# (C) 2016 Michael Rice <michael.rice@rackspace.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install distro packages
  package:
    pkg: "{{ cloudkitty_distro_packages }}"
    state: "{{ cloudkitty_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in cloudkitty_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: cloudkitty_developer_mode | bool
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Install requires pip packages
  pip:
    name: "{{ cloudkitty_requires_pip_packages }}"
    state: "{{ cloudkitty_pip_package_state }}"
    extra_args: >-
      {{ cloudkitty_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Retrieve checksum for venv download
  uri:
    url: "{{ cloudkitty_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: cloudkitty_venv_checksum
  when: cloudkitty_venv_download | bool
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Attempt venv download
  get_url:
    url: "{{ cloudkitty_venv_download_url }}"
    dest: "/var/cache/{{ cloudkitty_venv_download_url | basename }}"
    checksum: "sha1:{{ cloudkitty_venv_checksum.content | trim }}"
  register: cloudkitty_get_venv
  when: cloudkitty_venv_download | bool
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Remove existing venv
  file:
    path: "{{ cloudkitty_bin | dirname }}"
    state: absent
  when: cloudkitty_get_venv | changed
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Create cloudkitty venv dir
  file:
    path: "{{ cloudkitty_bin | dirname }}"
    state: directory
  register: cloudkitty_venv_dir
  when: cloudkitty_get_venv | changed
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ cloudkitty_venv_download_url | basename }}"
    dest: "{{ cloudkitty_bin | dirname }}"
    copy: "no"
  when: cloudkitty_get_venv | changed
  notify:
    - Restart cloudkitty services
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

- name: Install pip packages
  pip:
    name: "{{ cloudkitty_pip_packages }}"
    state: "{{ cloudkitty_pip_package_state }}"
    virtualenv: "{{ cloudkitty_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ cloudkitty_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: cloudkitty_get_venv | failed or cloudkitty_get_venv | skipped
  notify:
    - Restart cloudkitty services
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages

# NOTE(odyssey4me):
# We reinitialize the venv to ensure that the right
# version of python is in the venv, but we do not
# want virtualenv to also replace pip, setuptools
# and wheel so we tell it not to.
# We do not use --always-copy for CentOS/SuSE due
# to https://github.com/pypa/virtualenv/issues/565
- name: Update virtualenv path
  shell: |
    find {{ cloudkitty_bin }} -name \*.pyc -delete
    sed -si '1s/^.*python.*$/#!{{ cloudkitty_bin | replace ('/','\/') }}\/python/' {{ cloudkitty_bin }}/*
    virtualenv {{ cloudkitty_bin | dirname }} \
        {{ (ansible_pkg_mgr == 'apt') | ternary('--always-copy', '') }} \
        --no-pip \
        --no-setuptools \
        --no-wheel
  when: cloudkitty_get_venv | changed
  tags:
    - skip_ansible_lint
  tags:
    - cloudkitty-install
    - cloudkitty-pip-packages
